steps:
# This step will build and push new container image to "google container registry(GCR)"
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/fnote-taking-gke-dev', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/fnote-taking-gke-dev']

# # This step will deploy the new container image to cloud run
# - name: 'gcr.io/cloud-builders/gcloud'
#   args: ['run','deploy', 'fnote-taking-service', '--image=gcr.io/$PROJECT_ID/fnote-taking', '--region=us-west4', '--allow-unauthenticated']

# This step is to deploy container to GKE 
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
     - run
     - --filename=gke.yaml
     - --image=gcr.io/$PROJECT_ID/fnote-taking-gke-dev
     - --location=us-central1-c
     - --cluster=cluster-1
     - --namespace=dev