apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fnote-taking-gke-deploy
  name: fnote-taking-gke-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fnote-taking-gke-deploy
  template:
    metadata:
      labels:
        app: fnote-taking-gke-deploy
    spec:
      containers:
      - image: gcr.io/fnote-taking-gcp-ci-cd-gke/fnote-taking-gke-dev:latest 
        name: fnote-taking-gke-dev
        ports:
          - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fnote-taking-gke-deploy
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
  name: fnote-taking-gke-deploy
  namespace: dev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: fnote-taking-gke-deploy
  type: "LoadBalancer"
